services:
  - type: web
    name: telegram-bot
    plan: free
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 7704297977:AAG2_JbaZFMTcdPt4qGKxiUosUwB7Uud1AE
      - key: PORT
        value: 5000
      - key: WEBHOOK_PORT
        value: 3000
      - key: RENDER_EXTERNAL_HOSTNAME
        sync: false  # Автоматически подставится Render
    healthCheckPath: /